Resources:
  qualysScanner:
    Type: AWS::ECS::TaskDefinition
    Properties:
      ContainerDefinitions:
        -
          Image: sensor:latest
          Memory: 512
          Name: qualys-container-sensor
          Cpu: 10
          Command:
            - "--ecs=mode"
          Essential: True
